version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: ktor-mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
