### Create a new bike
POST http://localhost:8080/advertisement/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteUF1ZGllbmNlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvIiwidXNlcklkIjoxLCJleHAiOjE3NjE1ODU1MTV9.dGumQZH9nidyE3xxc6blUf4w_HlFSNp7fQlTb3ko8bc

{
  "bikeId": 1,
  "address": {
    "street": "Hogeschoollaan",
    "city": "Breda",
    "postalCode": "1011AA",
    "houseNumber": 17,
    "subHouseNumber": "a"
  },
  "availableFrom": "2020-08-30T18:43",
  "availableUntil": "2020-08-30T18:43",
  "price": 299.99
}