### Create a new bike
POST http://localhost:8080/bike/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteUF1ZGllbmNlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvIiwidXNlcklkIjoxLCJleHAiOjE3NjE1ODU1MTV9.dGumQZH9nidyE3xxc6blUf4w_HlFSNp7fQlTb3ko8bc

{
  "fuelType": "ICE",
  "bodyType": "NAKED",
  "brand": "BMW",
  "modelYear": "2017",
  "model": "r1200gs",
  "licensePlate": "KTR-123-B",
  "mileage": "34000",
  "createdStamp": "2020-08-30T18:43",
  "bikeImages": [
    {
      "image": "Image1"
    },
    {
      "image": "Image2"
    }
  ]
}

### Update existing bike
PUT http://localhost:8080/bike/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteUF1ZGllbmNlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvIiwidXNlcklkIjoxLCJleHAiOjE3NjE1ODU1MTV9.dGumQZH9nidyE3xxc6blUf4w_HlFSNp7fQlTb3ko8bc

{
  "fuelType": "ICE",
  "bodyType": "NAKED",
  "brand": "BMW",
  "modelYear": "2017",
  "model": "r1200gs",
  "licensePlate": "KTR-123-B",
  "mileage": "34000",
  "createdStamp": "2020-08-30T18:43",
  "bikeImages": [
    {
      "image": "Image1"
    },
    {
      "image": "Image2"
    },
    {
      "image": "Image3"
    }
  ]
}
