### Create a new Bike
POST http://localhost:8080/Bike/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteUF1ZGllbmNlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvIiwidXNlcklkIjoxLCJleHAiOjE3NjE0NzM3NDh9.M3YtNd8J0V4j0yzZe86YypNkNEthPkpJaft6F6Zimcw

{
  "fuelType": "ICE",
  "bodyType": "SEDAN",
  "brand": "Toyota",
  "modelYear": "2022",
  "model": "Supra",
  "licensePlate": "KTR-123-B",
  "mileage": "34000",
  "createdStamp": "2020-08-30T18:43",
  "BikeImages": [
    {
      "image": "base64EncodedImageStringHere"
    },
    {
      "image": "anotherBase64EncodedImageStringHere"
    }
  ]
}

### Update existing Bike
PUT http://localhost:8080/Bike/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteUF1ZGllbmNlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvIiwidXNlcklkIjoxLCJleHAiOjE3NjE0NzM3NDh9.M3YtNd8J0V4j0yzZe86YypNkNEthPkpJaft6F6Zimcw

{
  "fuelType": "ICE",
  "bodyType": "SEDAN",
  "brand": "Toyota",
  "modelYear": "2023",
  "model": "Supra",
  "licensePlate": "KTR-123-A",
  "mileage": "34500",
  "createdStamp": "2025-10-23T10:00:00",
  "BikeImages": [
    { "image": "image1_base64_or_url_here" },
    { "image": "image2_base64_or_url_here" }
  ]
}
