### Rent advertisement
POST http://localhost:8080/rent/advertisement
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteUF1ZGllbmNlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvIiwidXNlcklkIjoxLCJleHAiOjE3NjE1ODU1MTV9.dGumQZH9nidyE3xxc6blUf4w_HlFSNp7fQlTb3ko8bc

{
  "advertisementId": 1,
  "rentalStatus": "PENDING",
  "pickUpDate": "2025-10-18T14:30:00",
  "returningDate": "2025-10-18T14:30:00"
}

### Cancel rental
POST http://localhost:8080/rental/cancel/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteUF1ZGllbmNlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvIiwidXNlcklkIjoxLCJleHAiOjE3NjE1ODU1MTV9.dGumQZH9nidyE3xxc6blUf4w_HlFSNp7fQlTb3ko8bc

### Approve rental
POST http://localhost:8080/rental/approve/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteUF1ZGllbmNlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvIiwidXNlcklkIjoxLCJleHAiOjE3NjE1ODMwMTJ9.WzBO6Lt8Rg3A_YOLx5LWagJh1J-bDrvEn3dLq0Hg-zI
