### Create a new user with address
POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "koen@silvas.nl",
  "userType": "CUSTOMER",
  "password": "welkom123",
  "firstName": "Koen",
  "lastName": "Vergeer",
  "phone": "06 123456789",
  "userPoints": 0,
  "address": {
    "street": "Hogeschoollaan",
    "city": "Breda",
    "postalCode": "1011AA",
    "houseNumber": 31,
    "subHouseNumber": "a"
  }
}

