### Get Bike by ID
GET http://localhost:8080/Bike/show/21
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteUF1ZGllbmNlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvIiwidXNlcklkIjoxLCJleHAiOjE3NjExNDcyNzF9.yxv45vaZq3UGkwSHy8HEXCKhfkexAt4z3Eaw-koU3hw

### Get Bike personal Bikes
GET http://localhost:8080/personal/Bikes
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteUF1ZGllbmNlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvIiwidXNlcklkIjoxLCJleHAiOjE3NjExNDcyNzF9.yxv45vaZq3UGkwSHy8HEXCKhfkexAt4z3Eaw-koU3hw

