### Delete bike
DELETE http://localhost:8080/bike/delete/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteUF1ZGllbmNlIiwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3QvIiwidXNlcklkIjoxLCJleHAiOjE3NjE0NzM3NDh9.M3YtNd8J0V4j0yzZe86YypNkNEthPkpJaft6F6Zimcw
